pipeline:
  name: Build MERN-Stack-Example
  identifier: Build_SomaRohit_MERN_Stack_Example_1718168216090
  projectIdentifier: Sampleproject
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      cd server
                      yarn install;
                      yarn test;
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: somarohit
        repoName: MERN-Stack-Example
        build: <+input>
