pipeline:
  name: Build MERN-Stack-Example
  identifier: Build_SomaRohit_MERN_Stack_Example_1718168216090
  projectIdentifier: Sampleproject
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: initializing dependencies
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: |-
                      cd server
                      yarn install;
                      echo "LINE 3"
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: somaarohit
        repoName: MERN-Stack-Example
        build: <+input>
